Repository US-EPA-CAMD/easey-design-system, pull requests merged in 2021-12, with the labels that each got.

#21 fix(contactform): added aria-live to alerts in ContactForm
  src/components/ContactForm/ContactForm.tsx
Labels: Datateers

#22 Feat/global fonts
  .storybook/preview.scss
  package.json
  src/additional-scss/_easey-design-styles.scss
  src/additional-scss/_global-overrides.scss
  src/additional-scss/_global-styles.scss
  src/additional-scss/_variables.scss
  yarn.lock
Labels: enhancement

#23 Progress-Bar
  package.json
  src/components/TitledProgressBar/TitledProgressBar.scss
  src/components/TitledProgressBar/TitledProgressBar.stories.tsx
  src/components/TitledProgressBar/TitledProgressBar.tsx
  src/components/index.ts
  yarn.lock
Labels: Emissioners, Tech Team

#24 Progress-Bar
  src/components/TitledProgressBar/TitledProgressBar.scss
Labels: Emissioners, Tech Team
